export const translateCityName: { [x: string]: string } = {
  Samara: 'Самара',
  Ulyanovsk: 'Ульяновск',
  Saransk: 'Саранск',
  Kazan: 'Казань',
  Krasnodar: 'Краснодар',
  Ufa: 'Уфа',
  Saratov: 'Саратов',
  Volgograd: 'Волгоград',
  Voronezh: 'Воронеж',
  Sterlitamak: 'Стерлитамак',
  Tambov: 'Тамбов',
  Arkhangelsk: 'Архангельск',
  Krasnoyarsk: 'Красноярск',
  'Naberezhnye Chelny': 'Набережные челны',
};

export const orderValues = {
  orderStatusId: {},
  cityId: {},
  pointId: {},
  carId: {},
  color: 'string',
  dateFrom: 0,
  dateTo: 0,
  rateId: {},
  price: 0,
  isFullTank: true,
  isNeedChildChair: true,
  isRightWheel: true,
};
